# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models

from arsenal_stats.models import Player


def add_data(apps, schema_editor):
    Player.objects.create(full_name="Hector Bellerin", position="RB", age=21, number=24, games_started=36, goals_scored=1, assists=5, yellow_cards=3, red_cards=0)
    Player.objects.create(full_name="Nacho Monreal", position="LB", age=30, number=18, games_started=36, goals_scored=0, assists=3, yellow_cards=1, red_cards=0)
    Player.objects.create(full_name="Mesut Ozil", position="CAM", age=27, number=11, games_started=35, goals_scored=6, assists=19, yellow_cards=4, red_cards=0)
    Player.objects.create(full_name="Laurent Koscielny", position="CB", age=30, number=6, games_started=33, goals_scored=4, assists=0, yellow_cards=3, red_cards=0)
    Player.objects.create(full_name="Aaron Ramsey", position="CM", age=25, number=16, games_started=29, goals_scored=5, assists=4, yellow_cards=4, red_cards=0)
    Player.objects.create(full_name="Alexis Sanchez", position="F", age=27, number=17, games_started=28, goals_scored=13, assists=4, yellow_cards=1, red_cards=0)
    Player.objects.create(full_name="Olivier Giroud", position="ST", age=29, number=12, games_started=26, goals_scored=12, assists=6, yellow_cards=2, red_cards=0)
    Player.objects.create(full_name="Per Mertesacker", position="CB", age=31, number=4, games_started=24, goals_scored=0, assists=0, yellow_cards=1, red_cards=1)
    Player.objects.create(full_name="Francis Coquelin", position="CDM", age=25, number=34, games_started=21, goals_scored=0, assists=0, yellow_cards=5, red_cards=1)


class Migration(migrations.Migration):

    dependencies = [
        ('arsenal_stats', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
